# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seashell_with_layouts.ui',
# licensing of 'seashell_with_layouts.ui' applies.
#
# Created: Fri Jul 30 18:22:08 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.audioTree = FolderTree(self.tab)
        self.audioTree.setObjectName("audioTree")
        self.audioTree.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.audioTree)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fileTimer = AudioSlider(self.tab)
        self.fileTimer.setOrientation(QtCore.Qt.Horizontal)
        self.fileTimer.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fileTimer.setObjectName("fileTimer")
        self.horizontalLayout_7.addWidget(self.fileTimer)
        self.fileLoadButton = QtWidgets.QPushButton(self.tab)
        self.fileLoadButton.setObjectName("fileLoadButton")
        self.horizontalLayout_7.addWidget(self.fileLoadButton)
        self.fileTimerLabel = QtWidgets.QLabel(self.tab)
        self.fileTimerLabel.setText("")
        self.fileTimerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fileTimerLabel.setObjectName("fileTimerLabel")
        self.horizontalLayout_7.addWidget(self.fileTimerLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.loadFileLabel = QtWidgets.QLabel(self.tab)
        self.loadFileLabel.setText("")
        self.loadFileLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.loadFileLabel.setMargin(3)
        self.loadFileLabel.setIndent(-5)
        self.loadFileLabel.setObjectName("loadFileLabel")
        self.verticalLayout_4.addWidget(self.loadFileLabel)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setContentsMargins(2, -1, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cutoffCheck = QtWidgets.QCheckBox(self.frame_6)
        self.cutoffCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cutoffCheck.setChecked(True)
        self.cutoffCheck.setObjectName("cutoffCheck")
        self.horizontalLayout_6.addWidget(self.cutoffCheck)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.cutoffBox = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.cutoffBox.setMinimum(-9999.0)
        self.cutoffBox.setMaximum(9999.99)
        self.cutoffBox.setProperty("value", -4.0)
        self.cutoffBox.setObjectName("cutoffBox")
        self.horizontalLayout_6.addWidget(self.cutoffBox)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(2, 5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dec_combo = QtWidgets.QComboBox(self.frame_6)
        self.dec_combo.setObjectName("dec_combo")
        self.dec_combo.addItem("")
        self.dec_combo.addItem("")
        self.dec_combo.addItem("")
        self.horizontalLayout_4.addWidget(self.dec_combo)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.n_fft_combo = QtWidgets.QComboBox(self.frame_6)
        self.n_fft_combo.setObjectName("n_fft_combo")
        self.n_fft_combo.addItem("")
        self.n_fft_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.n_fft_combo)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tpsw_check = QtWidgets.QCheckBox(self.frame_6)
        self.tpsw_check.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tpsw_check.setChecked(True)
        self.tpsw_check.setObjectName("tpsw_check")
        self.verticalLayout_5.addWidget(self.tpsw_check)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.refresh_combo = QtWidgets.QComboBox(self.tab_3)
        self.refresh_combo.setObjectName("refresh_combo")
        self.refresh_combo.addItem("")
        self.refresh_combo.addItem("")
        self.refresh_combo.addItem("")
        self.refresh_combo.addItem("")
        self.refresh_combo.addItem("")
        self.horizontalLayout_8.addWidget(self.refresh_combo)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playButton = QtWidgets.QPushButton(self.frame_4)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_3.addWidget(self.playButton)
        self.pauseButton = QtWidgets.QPushButton(self.frame_4)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_3.addWidget(self.pauseButton)
        self.resetbutton = QtWidgets.QPushButton(self.frame_4)
        self.resetbutton.setObjectName("resetbutton")
        self.horizontalLayout_3.addWidget(self.resetbutton)
        self.verticalLayout.addWidget(self.frame_4)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 468, 221))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modelTable = ModelTable(self.scrollAreaWidgetContents_2)
        self.modelTable.setAlternatingRowColors(True)
        self.modelTable.setGridStyle(QtCore.Qt.DashLine)
        self.modelTable.setRowCount(0)
        self.modelTable.setColumnCount(3)
        self.modelTable.setObjectName("modelTable")
        self.modelTable.setColumnCount(3)
        self.modelTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.modelTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.modelTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.modelTable.setHorizontalHeaderItem(2, item)
        self.modelTable.horizontalHeader().setVisible(True)
        self.horizontalLayout.addWidget(self.modelTable)
        self.modelTree = ModelTree(self.scrollAreaWidgetContents_2)
        self.modelTree.setHeaderHidden(False)
        self.modelTree.setObjectName("modelTree")
        self.modelTree.header().setVisible(True)
        self.modelTree.header().setCascadingSectionResizes(False)
        self.horizontalLayout.addWidget(self.modelTree)
        self.horizontalLayout.setStretch(0, 11)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.modelInfo = ModelInfo(self.scrollAreaWidgetContents_2)
        self.modelInfo.setObjectName("modelInfo")
        self.verticalLayout_2.addWidget(self.modelInfo)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setAutoFillBackground(False)
        self.tab_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.modelPlot = ModelPlot(self.tab_5)
        self.modelPlot.setObjectName("modelPlot")
        self.verticalLayout_8.addWidget(self.modelPlot)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timePlot = TimePlot(self.frame_2)
        self.timePlot.setObjectName("timePlot")
        self.widget_3 = TimePlot(self.timePlot)
        self.widget_3.setGeometry(QtCore.QRect(340, 300, 611, 531))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4.addWidget(self.timePlot, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 15)
        self.verticalLayout.setStretch(3, 8)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.specPlot = SpectrogramWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specPlot.sizePolicy().hasHeightForWidth())
        self.specPlot.setSizePolicy(sizePolicy)
        self.specPlot.setObjectName("specPlot")
        self.gridLayout_3.addWidget(self.specPlot, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.fileLoadButton.setText(QtWidgets.QApplication.translate("MainWindow", "Unload", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Files", None, -1))
        self.cutoffCheck.setText(QtWidgets.QApplication.translate("MainWindow", "Spectrum Cutoff", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "(dB)", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Decimation", None, -1))
        self.dec_combo.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.dec_combo.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.dec_combo.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.dec_combo.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Window Size", None, -1))
        self.n_fft_combo.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1024", None, -1))
        self.n_fft_combo.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "2048", None, -1))
        self.tpsw_check.setText(QtWidgets.QApplication.translate("MainWindow", "TPSW", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "LOFAR", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh rate", None, -1))
        self.refresh_combo.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.refresh_combo.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.refresh_combo.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "15", None, -1))
        self.refresh_combo.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.refresh_combo.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "60", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "ups", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Configuration", None, -1))
        self.playButton.setText(QtWidgets.QApplication.translate("MainWindow", "Play", None, -1))
        self.pauseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.resetbutton.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.modelTable.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Model", None, -1))
        self.modelTable.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.modelTable.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Confidence", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Model Info", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtWidgets.QApplication.translate("MainWindow", "Model Plot", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))

from plots import TimePlot, ModelPlot, SpectrogramWidget
from utils import AudioSlider, FolderTree, ModelTable, ModelInfo, ModelTree
